Repository TeamSeeMeet/SeeMeet-iOS, pull requests merged in 2022-02, with the labels that each got.

#79 [FEAT] 바텀 시트 뷰 팬제스처 추가
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/RequestPlansDateVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/SelectedDateSheet.swift
Labels: enhancement, 킹 짱 환, 약속신청

#80 [FEAT] 약속 신청 뷰 세부 수정사항 기능 구현완료
  SeeMeet/SeeMeet/Source/Models/FriendsScene/FriendsListDataModel.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/ChipView.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/RequestPlansContentsVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/RequestPlansDateVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/SelectedDateSheet.swift
Labels: enhancement, 약속신청, 킹 짱 진

#82 [FEAT] Crashlytics 설정
  SeeMeet/Podfile
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/GoogleService-Info.plist
  SeeMeet/SeeMeet/Source/Support/AppDelegate.swift
Labels: enhancement, 킹 짱 환

#84 [REFACTOR] 약속 신청 뷰 리팩토링
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Xibs/TVC/RequestScene/SelectedDateSheetTVC.swift
  SeeMeet/SeeMeet/Resource/Xibs/TVC/RequestScene/SelectedDateSheetTVC.xib
  SeeMeet/SeeMeet/Source/Services/RequestScene/PostRequestPlansService.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/Components/ChipView.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/Components/DayCellView.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/Components/SelectedDateSheet.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/PickedDate.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/RequestPlansContentsVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/RequestPlansDateVC.swift
Labels: enhancement, 킹 짱 환, 약속신청
