Repository TeamSeeMeet/SeeMeet-iOS, pull requests merged in 2022-01, with the labels that each got.

#5 [FEAT] 하단 탭바
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_send-message.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_send-message.imageset/btn_send-message.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_send-message.imageset/btn_send-message@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_send-message.imageset/btn_send-message@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/calendar_ic.imageset/Component 89.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/calendar_ic.imageset/Component 89@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/calendar_ic.imageset/Component 89@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/calendar_ic.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/calendar_ic_clicked.imageset/Component 89.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/calendar_ic_clicked.imageset/Component 89@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/calendar_ic_clicked.imageset/Component 89@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/calendar_ic_clicked.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/home_ic.imageset/Component 88.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/home_ic.imageset/Component 88@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/home_ic.imageset/Component 88@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/home_ic.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/home_ic_clicked.imageset/Component 88.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/home_ic_clicked.imageset/Component 88@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/home_ic_clicked.imageset/Component 88@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/home_ic_clicked.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Info.plist
  SeeMeet/SeeMeet/Resource/Storyboards/Tabbar/Tabbar.storyboard
  SeeMeet/SeeMeet/Source/Views/VCs/Tabbar/TabbarVC.swift
Labels: enhancement, 킹 짱 범

#2 [FEAT] 메인 뷰 레이아웃 구현
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Assets.xcassets/Ellipse_dummy.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/Ellipse_dummy.imageset/Ellipse_dummy.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/Ellipse_dummy.imageset/Ellipse_dummy@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/Ellipse_dummy.imageset/Ellipse_dummy@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/Image_dummy.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/Image_dummy.imageset/Image_dummy.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/Image_dummy.imageset/Image_dummy@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/Image_dummy.imageset/Image_dummy@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_friends.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_friends.imageset/btn_friends.svg
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_friends.imageset/btn_friends@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_friends.imageset/btn_friends@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_menu.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_menu.imageset/btn_menu.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_menu.imageset/btn_menu@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_menu.imageset/btn_menu@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/profile_Dummy.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/profile_Dummy.imageset/profile_Dummy.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/profile_Dummy.imageset/profile_Dummy@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/profile_Dummy.imageset/profile_Dummy@3x.png
  SeeMeet/SeeMeet/Resource/Xibs/CVC/HomeScene/HomeEventCVC.xib
  SeeMeet/SeeMeet/Resource/Xibs/CVC/dummy2.swift
  SeeMeet/SeeMeet/Source/Extension/UIColor++.swift
  SeeMeet/SeeMeet/Source/Extension/UIView++.swift
  SeeMeet/SeeMeet/Source/Views/Cells/CVC/HomeScene/HomeEventCVC.swift
  SeeMeet/SeeMeet/Source/Views/Cells/CVC/dummy4.swift
  SeeMeet/SeeMeet/Source/Views/VCs/HomeScene/HomeVC.swift
Labels: 킹 짱 범, 메인

#12 [FEAT] 약속 리스트 뷰 구현
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_back.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_back.imageset/btn_back.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_back.imageset/btn_back@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_back.imageset/btn_back@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_close.imageset/Component 184.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_close.imageset/Component 184@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_close.imageset/Component 184@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_close.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_plansName.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_plansName.imageset/Frame 216.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_plansName.imageset/Frame 216@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_plansName.imageset/Frame 216@3x.png
  SeeMeet/SeeMeet/Resource/Storyboards/PlansScene/PlansList.storyboard
  SeeMeet/SeeMeet/Resource/Storyboards/Tabbar/Tabbar.storyboard
  SeeMeet/SeeMeet/Resource/Xibs/CVC/PlansScene/CompletePlansCVC.xib
  SeeMeet/SeeMeet/Resource/Xibs/CVC/PlansScene/ProgressReceiveCVC.xib
  SeeMeet/SeeMeet/Resource/Xibs/CVC/PlansScene/ProgressSendCVC.xib
  SeeMeet/SeeMeet/Source/Views/Cells/CVC/PlansScene/CompletePlansCVC.swift
  SeeMeet/SeeMeet/Source/Views/Cells/CVC/PlansScene/ProgressReceiveCVC.swift
  SeeMeet/SeeMeet/Source/Views/Cells/CVC/PlansScene/ProgressSendCVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/HomeScene/HomeVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/PlansScene/PlansListVC.swift
Labels: 킹 짱 범, 약속내역

#21 [FEAT] 약속신청 첫번째 화면 기본 레이아웃 구현
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_close.imageset/btn_close.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_close.imageset/btn_close@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_close.imageset/btn_close@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_embody.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_embody.imageset/btn_embody.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_embody.imageset/btn_embody@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_embody.imageset/btn_embody@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_plus.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_plus.imageset/btn_plus.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_plus.imageset/btn_plus@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_plus.imageset/btn_plus@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_remove.imageset/btn_remove.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_remove.imageset/btn_remove@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_remove.imageset/btn_remove@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_search.imageset/ic_ search.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_search.imageset/ic_ search@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_search.imageset/ic_ search@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_profile.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_profile.imageset/img_profile.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_profile.imageset/img_profile@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_profile.imageset/img_profile@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/property1Black.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/property1Black.imageset/property1Black.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/property1Black.imageset/property1Black@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/property1Black.imageset/property1Black@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/property1Grey.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/property1Grey.imageset/property1Grey.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/property1Grey.imageset/property1Grey@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/property1Grey.imageset/property1Grey@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/property1White.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/property1White.imageset/property1White.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/property1White.imageset/property1White@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/property1White.imageset/property1White@3x.png
  SeeMeet/SeeMeet/Resource/Storyboards/RequestScene/RequestPlansContents.storyboard
  SeeMeet/SeeMeet/Resource/Xibs/CVC/HomeScene/HomeEventCVC.xib
  SeeMeet/SeeMeet/Source/Extension/UITextField++.swift
  SeeMeet/SeeMeet/Source/Views/Cells/TVC/RequestScene/SearchTVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/ChipView.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/RequestPlansContentsVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/Tabbar/TabbarVC.swift
Labels: enhancement, 약속신청, 킹 짱 진

#23 [FEAT] 약속 신청 뷰 하단 시트 뷰 컴포넌트 구현
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_remove_black.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_remove_black.imageset/btnRemoveBlack.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_remove_black.imageset/btnRemoveBlack@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_remove_black.imageset/btnRemoveBlack@3x.png
  SeeMeet/SeeMeet/Resource/Storyboards/SelectedDateSheet.xib
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/DateTicketView.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/SelectedDateSheet.swift
Labels: enhancement, 킹 짱 환, 약속신청

#18 [FEAT] 받은 약속 내역 리스트 구현
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet.xcodeproj/xcshareddata/xcschemes/SeeMeet 1.xcscheme
  SeeMeet/SeeMeet.xcodeproj/xcshareddata/xcschemes/SeeMeet.xcscheme
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_check_active.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_check_active.imageset/Property 1=ic_check_active.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_check_active.imageset/Property 1=ic_check_active@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_check_active.imageset/Property 1=ic_check_active@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_check_grey.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_check_grey.imageset/Property 1=ic_check_grey.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_check_grey.imageset/Property 1=ic_check_grey@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_check_grey.imageset/Property 1=ic_check_grey@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_finish_check_inactive.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_finish_check_inactive.imageset/Property 1=ic_finish_check_inactive.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_finish_check_inactive.imageset/Property 1=ic_finish_check_inactive@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_finish_check_inactive.imageset/Property 1=ic_finish_check_inactive@3x.png
  SeeMeet/SeeMeet/Resource/Storyboards/PlansScene/PlansReceiveList.storyboard
  SeeMeet/SeeMeet/Resource/Xibs/CVC/PlansScene/PlansReceiveCVC.xib
  SeeMeet/SeeMeet/Source/Extension/UILabel++.swift
  SeeMeet/SeeMeet/Source/Views/Cells/CVC/PlansScene/PlansReceiveCVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/PlansScene/PlansListVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/PlansScene/PlansReceiveVC.swift
Labels: 킹 짱 범, 약속내역

#30 [FEAT] 두번째 레이아웃 구현
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_back.imageset/btn_back.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_back.imageset/btn_back@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_close_bold.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_close_bold.imageset/btn_close_bold.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_close_bold.imageset/btn_close_bold@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_close_bold.imageset/btn_close_bold@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_embody_on.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_embody_on.imageset/btn_embody_on.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_embody_on.imageset/btn_embody_on@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_embody_on.imageset/btn_embody_on@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/leftchevron.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/leftchevron.imageset/chevron_left.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/leftchevron.imageset/chevron_left@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/leftchevron.imageset/chevron_left@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/rightchevron.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/rightchevron.imageset/chevron_right.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/rightchevron.imageset/chevron_right@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/rightchevron.imageset/chevron_right@3x.png
  SeeMeet/SeeMeet/Resource/Storyboards/RequestScene/RequestPlansDate.storyboard
  SeeMeet/SeeMeet/Source/Views/Cells/TVC/RequestScene/ScheduleTVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/DayCellView.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/RequestPlansContentsVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/RequestPlansDateVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/SelectedDateSheet.swift
Labels: enhancement, 약속신청, 킹 짱 진

#27 [FEAT] 약속 리스트 뷰 커스텀 알러트 레이아웃 구현
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Storyboards/SMRequestPopUp.storyboard
  SeeMeet/SeeMeet/Source/Views/VCs/PlansScene/PlansReceiveVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/PlansScene/PlansSendListVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/SMRequestPopUpVC.swift
Labels: 킹 짱 범, 약속내역

#28 [FEAT] 로그인 뷰 레이아웃 구현완료
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_sign-up.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_sign-up.imageset/btn_sign-up.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_sign-up.imageset/btn_sign-up@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/btn_sign-up.imageset/btn_sign-up@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_e-mail.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_e-mail.imageset/ic_e-mail.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_e-mail.imageset/ic_e-mail@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_e-mail.imageset/ic_e-mail@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_password.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_password.imageset/ic_password.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_password.imageset/ic_password@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_password.imageset/ic_password@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_password_notsee.imageset/Component 261.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_password_notsee.imageset/Component 261@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_password_notsee.imageset/Component 261@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_password_notsee.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_password_see.imageset/Component 261.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_password_see.imageset/Component 261@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_password_see.imageset/Component 261@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_password_see.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_seemeet_logo.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_seemeet_logo.imageset/img_seemeet_logo_symbol+typo_square.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_seemeet_logo.imageset/img_seemeet_logo_symbol+typo_square@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_seemeet_logo.imageset/img_seemeet_logo_symbol+typo_square@3x.png
  SeeMeet/SeeMeet/Resource/Info.plist
  SeeMeet/SeeMeet/Resource/Storyboards/LoginScene/Login.storyboard
  SeeMeet/SeeMeet/Source/Views/VCs/GrayTextField.swift
  SeeMeet/SeeMeet/Source/Views/VCs/GrayTextView.swift
  SeeMeet/SeeMeet/Source/Views/VCs/LoginScene/LoginVC.swift
Labels: 킹 짱 범, 로그인

#33 [FEAT] 회원가입 뷰 구현 및 서버 연동
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Storyboards/RegisterScene/Register.storyboard
  SeeMeet/SeeMeet/Source/Models/RegisterDataModel.swift
  SeeMeet/SeeMeet/Source/Models/dummy123.swift
  SeeMeet/SeeMeet/Source/Services/PostRegisterService.swift
  SeeMeet/SeeMeet/Source/Services/TokenUtils.swift
  SeeMeet/SeeMeet/Source/Views/VCs/GrayTextField.swift
  SeeMeet/SeeMeet/Source/Views/VCs/LoginScene/LoginVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RegisterScene/RegisterVC.swift
Labels: 회원가입

#37 [FEAT] 메인화면 서버 연동 완료
  SeeMeet/Podfile
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_noti.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_noti.imageset/Group 1387.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_noti.imageset/Group 1387@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_noti.imageset/Group 1387@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_1.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_1.imageset/img_illust_1.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_1.imageset/img_illust_1@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_1.imageset/img_illust_1@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_10.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_10.imageset/img_illust_10.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_10.imageset/img_illust_10@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_10.imageset/img_illust_10@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_2.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_2.imageset/img_illust_2.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_2.imageset/img_illust_2@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_2.imageset/img_illust_2@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_3.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_3.imageset/img_illust_3.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_3.imageset/img_illust_3@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_3.imageset/img_illust_3@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_4.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_4.imageset/img_illust_4.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_4.imageset/img_illust_4@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_4.imageset/img_illust_4@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_5.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_5.imageset/img_illust_5.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_5.imageset/img_illust_5@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_5.imageset/img_illust_5@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_6.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_6.imageset/img_illust_6.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_6.imageset/img_illust_6@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_6.imageset/img_illust_6@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_7.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_7.imageset/img_illust_7.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_7.imageset/img_illust_7@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_7.imageset/img_illust_7@3x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_8.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_8.imageset/img_illust_8.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_8.imageset/img_illust_8@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_8.imageset/img_illust_8@3x.png
  SeeMeet/SeeMeet/Resource/Info.plist
  SeeMeet/SeeMeet/Source/Models/FriendsListDataModel.swift
  SeeMeet/SeeMeet/Source/Models/HomeDataModel.swift
  SeeMeet/SeeMeet/Source/Models/LastDateDataModel.swift
  SeeMeet/SeeMeet/Source/Services/Constants.swift
  SeeMeet/SeeMeet/Source/Services/GetFriendsListService.swift
  SeeMeet/SeeMeet/Source/Services/GetHomeDataService.swift
  SeeMeet/SeeMeet/Source/Services/GetLastDateService.swift
  SeeMeet/SeeMeet/Source/Views/VCs/HomeScene/HomeVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/LoginScene/LoginVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RegisterScene/RegisterVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/Tabbar/TabbarVC.swift
Labels: 킹 짱 범, 메인

#39 Feature/32 networking add friends view
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Source/Models/MonthlyPlansResponseModel.swift
  SeeMeet/SeeMeet/Source/Services/CalendarService.swift
  SeeMeet/SeeMeet/Source/Views/Cells/CVC/CalendarScene/CalendarPlansCVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/CalendarScene/CalendarVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/Tabbar/TabbarVC.swift
Labels: enhancement, 킹 짱 환, 캘린더

#43 [FEAT] 약속 리스트 뷰 서버연동
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_9.imageset/img_illust_9.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_9.imageset/img_illust_9@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/img_illust_9.imageset/img_illust_9@3x.png
  SeeMeet/SeeMeet/Source/Models/PlansListDataModel.swift
  SeeMeet/SeeMeet/Source/Services/Constants.swift
  SeeMeet/SeeMeet/Source/Services/GetPlansListDataService.swift
  SeeMeet/SeeMeet/Source/Services/PostRegisterService.swift
  SeeMeet/SeeMeet/Source/Views/Cells/CVC/PlansScene/CompletePlansCVC.swift
  SeeMeet/SeeMeet/Source/Views/Cells/CVC/PlansScene/ProgressReceiveCVC.swift
  SeeMeet/SeeMeet/Source/Views/Cells/CVC/PlansScene/ProgressSendCVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/HomeScene/HomeVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/PlansScene/PlansListVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RegisterScene/RegisterVC.swift
Labels: 킹 짱 범, 약속내역

#47 [FEAT] 약속 신청 두번째 뷰 세부 레이아웃 구현 완료
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Source/Extension/Date++.swift
  SeeMeet/SeeMeet/Source/Extension/UIView++.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/DateTicketView.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/DayCellView.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/PickedDate.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/RequestPlansDateVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/SelectedDateSheet.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/WeekDay.swift
Labels: enhancement, 약속신청, 킹 짱 진

#48 [FEAT] 캘린더 상세 뷰 연결
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Source/Models/PlanDetailResponseModel.swift
  SeeMeet/SeeMeet/Source/Services/CalendarService.swift
  SeeMeet/SeeMeet/Source/Views/VCs/CalendarScene/CalendarDetailVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/CalendarScene/CalendarVC.swift
Labels: enhancement, 킹 짱 환, 캘린더

#52 [FEAT] 마이 페이지 상단 뷰컴포넌트 구현
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_mypage_login.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_mypage_login.imageset/icMypageLogin.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_mypage_login.imageset/icMypageLogin@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/ic_mypage_login.imageset/icMypageLogin@3x.png
  SeeMeet/SeeMeet/Resource/Xibs/MyPageTopView.xib
  SeeMeet/SeeMeet/Source/Views/VCs/MyPageTopView.swift
Labels: enhancement, 킹 짱 환, 마이페이지

#54 [FEAT] 마이 페이지 레이아웃 구현
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Assets.xcassets/my_page.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/my_page.imageset/my_page.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/my_page.imageset/my_page@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/my_page.imageset/my_page@3x.png
  SeeMeet/SeeMeet/Resource/Xibs/MyPageView.xib
  SeeMeet/SeeMeet/Source/Views/VCs/MyPageView.swift
Labels: enhancement, 킹 짱 환, 마이페이지

#56 [FEAT] 마이페이지 구현완료
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Resource/Storyboards/HomeScene/Home.storyboard
  SeeMeet/SeeMeet/Resource/Xibs/MyPageView.xib
  SeeMeet/SeeMeet/Source/Views/VCs/HomeScene/HomeVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/LoginScene/LoginVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/MyPageView.swift
  SeeMeet/SeeMeet/Source/Views/VCs/NewMyPageView.swift
Labels: 킹 짱 범, 마이페이지

#58 [FEAT] 확정된 약속 연결
  SeeMeet/SeeMeet/Source/Views/VCs/PlansScene/PlansListVC.swift
Labels: 킹 짱 범, 약속내역, 캘린더

#62 [FEAT] 스플래시 이미지 추가
  SeeMeet/SeeMeet/Resource/Assets.xcassets/dummyImageView.imageset/Contents.json
  SeeMeet/SeeMeet/Resource/Assets.xcassets/dummyImageView.imageset/dummyImageView.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/dummyImageView.imageset/dummyImageView@2x.png
  SeeMeet/SeeMeet/Resource/Assets.xcassets/dummyImageView.imageset/dummyImageView@3x.png
  SeeMeet/SeeMeet/Resource/Storyboards/LaunchScreen/Base.lproj/LaunchScreen.storyboard
  SeeMeet/SeeMeet/Source/Support/AppDelegate.swift
  SeeMeet/SeeMeet/Source/Views/VCs/NewMyPageView.swift
  SeeMeet/SeeMeet/Source/Views/VCs/RegisterScene/RegisterVC.swift
Labels: 킹 짱 범, 메인

#64 [FEAT] 디자인 QA수정
  SeeMeet/SeeMeet/Resource/Info.plist
  SeeMeet/SeeMeet/Source/Views/VCs/CalendarScene/CalendarDetailVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/PlansScene/PlansListVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/PlansScene/PlansReceiveVC.swift
  SeeMeet/SeeMeet/Source/Views/VCs/PlansScene/PlansSendListVC.swift
Labels: 킹 짱 범

#71 [MOVE] 네트워크 모델 및 서비스 Request Scene 부분 폴더링
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Source/Models/CalendarScene/MonthlyPlansResponseModel.swift
  SeeMeet/SeeMeet/Source/Models/CalendarScene/PlanDetailResponseModel.swift
  SeeMeet/SeeMeet/Source/Models/FriendsScene/FriendsAddResponseModel.swift
  SeeMeet/SeeMeet/Source/Models/FriendsScene/FriendsListDataModel.swift
  SeeMeet/SeeMeet/Source/Models/FriendsScene/FriendsSearchResponseModel.swift
  SeeMeet/SeeMeet/Source/Models/HomeScene/HomeDataModel.swift
  SeeMeet/SeeMeet/Source/Models/HomeScene/LastDateDataModel.swift
  SeeMeet/SeeMeet/Source/Models/PlansScene/PlansDetailDataModel.swift
  SeeMeet/SeeMeet/Source/Models/PlansScene/PlansListDataModel.swift
  SeeMeet/SeeMeet/Source/Models/PlansScene/PlansRequestAcceptDataModel.swift
  SeeMeet/SeeMeet/Source/Models/PlansScene/PlansSendDetailDataModel.swift
  SeeMeet/SeeMeet/Source/Models/PlansScene/ResponseDateDataModel.swift
  SeeMeet/SeeMeet/Source/Models/RegisterScene/RegisterDataModel.swift
  SeeMeet/SeeMeet/Source/Models/RequestScene/InvitationPlanDataModel.swift
  SeeMeet/SeeMeet/Source/Models/RequestScene/PlanRequestDataModel.swift
  SeeMeet/SeeMeet/Source/Services/RequestScene/GetScheduleService.swift
  SeeMeet/SeeMeet/Source/Services/RequestScene/PostRequestPlansService.swift
Labels: enhancement, 킹 짱 진

#73 Bug/72 request scene calendar day bug
  SeeMeet/SeeMeet.xcodeproj/project.pbxproj
  SeeMeet/SeeMeet/Source/Views/VCs/RequestScene/RequestPlansDateVC.swift
Labels: 킹 짱 진

#77 [FIX] 초대장 목록 뷰 네트워킹 오류 수정
  SeeMeet/SeeMeet/Source/Models/PlansScene/PlansListDataModel.swift
  SeeMeet/SeeMeet/Source/Services/GetPlansListDataService.swift
  SeeMeet/SeeMeet/Source/Views/VCs/PlansScene/PlansListVC.swift
Labels: bug
